# change the followings to match your Github username and repo name
baseurl: "/pb-tutor" # the name of your github repo
url: "https://neil-b-patel.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Peyton R.C. Blodgett"
description: Tutor, Teacher, & Thermostat

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Peyton R.C. Blodgett
author-bio: false # change to false to hide
author-image: image.png # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: https://instagram.com/
github: https://github.com/
linkedin: https://linkedin.com/
medium: https://medium.com/
google-scholar: https://scholar.google.com/
email: myexampleemailmakesurenobodyhasthis@email.com

# footer information
footer-msg: false
footer-msg-link: false

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
  - jekyll-seo-tag
